### PR TITLE
Fixes #93: Change dropdown menu to red on hover

### LINKED ISSUE #93: Red Drop Down Menu
Change FOSSASIA websites Common Drop Down Menu to Red (on hover)

### PR DESCRIPTION
**Pull request by Ploypiti**
#93 | [deploy link](https://ploypiti.github.io/2017.fossasia.org/)

### CODE REVIEW

**Comment by abishekvashok** [comment]
@Ploypiti why is this drop down a bit large?
screenshot_20180102_101529

**Comment by abishekvashok** [comment]
Intend and squash the code and this is ready to be shipped I guess.

**Review by nzec — APPROVED** [review]
Nice Work!

**Review by realslimshanky — APPROVED** [review]
LGTM

**Review by ParthS007 — APPROVED** [review]

**Pull request merged**
