### PR TITLE
Fixes #8

### LINKED ISSUE #8: Add GitHub icon in footer and sidebar
I suggest adding Github icon : 
1. To the sidebar, replacing dribble icon as it just redirects to fossaia.org
2. To the footer
page-shot-2016-10-2-fossasia 2017

Also, this issue (https://github.com/fossasia/fossasia.org/issues/66)  exists here too:
page-shot-2016-10-2-fossasia 2017 1

### PR DESCRIPTION
**Pull request by singhksandeep25**
Added GitHub icon on the sidebar and on the bottom. Also fixed overlapping of copyright text and other items in the sidebar.

### CODE REVIEW

**Comment by bettersandeep** [comment]
Added another commit which fixes #10

**Comment by jigyasa-grover** [comment]
@sandmanx Always post link to the demo to fasten the review process. 
Also, include before and after screenshots to emphasise on the changes done.

**Comment by bettersandeep** [comment]
Fixed #8 

Before:
page-shot-2016-10-2-fossasia 2017 3

After:
page-shot-2016-10-2-fossasia 2017

Fixed #10 
1. Before:

page-shot-2016-10-2-fossasia 2017 4

After:
page-shot-2016-10-2-fossasia 2017 1
1. Before:

page-shot-2016-10-2-fossasia 2017 5

After: 
page-shot-2016-10-2-fossasia 2017 2

Demo Link: https://sandmanx.github.io/ 
There might be a security error while loading javascript on the demo link, so please take care of that.

**Comment by bettersandeep** [comment]
@jig08 Done as you wanted.

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
