### PR TITLE
Indented the code

### PR DESCRIPTION
**Pull request by samyakbvs**

### CODE REVIEW

**Comment by samyakbvs** [comment]
#79

**Review by 0x48piraj — CHANGES_REQUESTED** [review]
`11,452 additions`

Why you re-done the whole file which is auto-generated?
It increases the chance for errors.

**Comment by samyakbvs** [comment]
I have just indented
nothing deleted

**Review by vaibhavsingh97 — COMMENTED** [review]
It's an autogenerated file so I don't think so we need indentation for this.
Cc @ParthS007 @harshit98 @ms10398

**Comment by samyakbvs** [comment]
What does cc stand for?

**Comment by mariobehling** [comment]
This can be done later. As the site was just broken, we need to follow best practices at FOSSASIA more closely. Please open an issue and follow best practices in your PRs.

@samyakbvs You are already made a number of PRs. We want to make it easy to start contributing in FOSSASIA, but we need to ensure new devs understand and learn about how to contribute in the project continuously. We also need to understand that all reviewers are volunteers and we should be savy with the time and resources of the community. Please follow best practices now and focus on substantial improvements preferably in our software projects: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Pull request closed without merging**
