### PR TITLE
Fixed Tweets and Red font on red button

### LINKED ISSUE #68: Load tweets using HTTPS
Load tweets via HTTPS
Use : https://github.com/fossasia/2018.fossasia.org/pull/32/commits/9f84dae03dbc7f7c09bd3489b588702b18642c56 for reference.

### LINKED ISSUE #69: Red font on red button
The font on top of some red buttons is also red now. Please help to fix it.

screenshot from 2017-12-13 23-11-57

### PR DESCRIPTION
**Pull request by nzec**
* Fixed Tweets and made them on https://
* Made all resources under https://
* Fixed Red font on red button problem
* Fixes #68 
* Fixes #69 

**Preview Link Here :** http://duttaditya18.github.io/2017.fossasia.org

---

### CODE REVIEW

**Comment by nzec** [comment]
@fossasia/web-developers @fossasia/website-admins @mariobehling

**Review by ba11b0y — APPROVED** [review]
LGTM!

**Comment by nzec** [comment]
@invinciblycool Thanks!

**Review by 0x48piraj — APPROVED** [review]
LGTM :rocket:

**Comment by nzec** [comment]
Thanks!

**Pull request merged**
